In [0]:
import numpy as np

### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
# https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html
np_array = np.random.randint(1,51,10)
np_array

Out[3]: array([14, 22, 26, 11, 29, 44, 23, 49, 46, 44])

In [0]:
# média
print("Média:" ,np.mean(np_array))

# desvio padrão
print("Desvio padrão: ", np.std(np_array))

Média: 30.8
Desvio padrão:  13.22724461102916


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
arr = np.random.rand(10)

print("Array original:\n",arr)

arr[arr<=0.5] = np.sqrt(arr[arr<=0.5])
print("\nRaiz quadrados dos valores <= 0.5\n", arr)

Array original:
 [0.20672316 0.47388621 0.67013968 0.85873161 0.9591795  0.1839679
 0.33636111 0.67112562 0.46727421 0.91802589]

Raiz quadrados dos valores <= 0.5
 [0.45466819 0.68839393 0.67013968 0.85873161 0.9591795  0.42891479
 0.57996648 0.67112562 0.68357459 0.91802589]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
arr = np.random.rand(3, 3, 3)
arr

Out[24]: array([[[0.67798511, 0.37710352, 0.33024092],
        [0.56001782, 0.89685249, 0.94946745],
        [0.92235997, 0.04718173, 0.61719338]],

       [[0.81468081, 0.57950218, 0.85780639],
        [0.78483062, 0.96823424, 0.6268648 ],
        [0.93359386, 0.99852219, 0.93083321]],

       [[0.36953109, 0.24390714, 0.39327666],
        [0.64622382, 0.9115084 , 0.6081093 ],
        [0.46903347, 0.37883895, 0.19155975]]])

In [0]:
for i in range(len(arr)):
  print("\n%dª Matriz 2D" %(i+1))
  for j in range(len(arr[i])):
    maximo = arr[i][j].max()
    print("%dª Linha da Matriz %d - Valor máximo: %f " %(j+1,i+1,maximo))
    


1ª Matriz 2D
1ª Linha da Matriz 1 - Valor máximo: 0.677985 
2ª Linha da Matriz 1 - Valor máximo: 0.949467 
3ª Linha da Matriz 1 - Valor máximo: 0.922360 

2ª Matriz 2D
1ª Linha da Matriz 2 - Valor máximo: 0.857806 
2ª Linha da Matriz 2 - Valor máximo: 0.968234 
3ª Linha da Matriz 2 - Valor máximo: 0.998522 

3ª Matriz 2D
1ª Linha da Matriz 3 - Valor máximo: 0.393277 
2ª Linha da Matriz 3 - Valor máximo: 0.911508 
3ª Linha da Matriz 3 - Valor máximo: 0.469033 


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
matriz = np.random.rand(5,5)
matriz

Out[48]: array([[0.44463293, 0.91772377, 0.78361243, 0.84277149, 0.14558837],
       [0.24850055, 0.39069072, 0.87631167, 0.09894832, 0.53727469],
       [0.2026828 , 0.8334761 , 0.4111463 , 0.11748172, 0.34885105],
       [0.38988396, 0.17295247, 0.26432965, 0.19939768, 0.60156832],
       [0.20433673, 0.5960396 , 0.03919506, 0.81062095, 0.95578968]])

In [0]:
media = np.mean(arr, axis=1)
linha_media = arr - media[:, np.newaxis]

print("Média das matrizes\n", media)
print("Matriz com a média de cada linha subtraída\n",linha_media)

Média das matrizes
 [[[[0.44945458 0.43824758 0.48697707 0.56436192 0.33508651]
   [0.40873317 0.38096867 0.5317713  0.61262178 0.51135113]
   [0.45049995 0.53081287 0.63123777 0.47953028 0.66628902]
   [0.37066261 0.66453801 0.26804316 0.53320519 0.58004887]
   [0.55601466 0.13916906 0.53972364 0.4997965  0.74538335]]

  [[0.61229554 0.63169906 0.78092463 0.41312272 0.56750034]
   [0.55506311 0.6248422  0.47875733 0.65646062 0.43539134]
   [0.47320634 0.42707023 0.49486812 0.31538959 0.48791736]
   [0.45086141 0.4854411  0.59794353 0.67859858 0.52909649]
   [0.75768466 0.61986581 0.6456266  0.28831897 0.62867874]]

  [[0.40400333 0.81026396 0.35196015 0.46664257 0.35269342]
   [0.24351595 0.54475168 0.27329258 0.35101274 0.59786987]
   [0.45780134 0.54511473 0.56854387 0.55320206 0.51181046]
   [0.57565864 0.45318054 0.38179406 0.33227654 0.54741403]
   [0.38602398 0.66692892 0.46454504 0.4856863  0.46720805]]

  [[0.68197154 0.46351104 0.52312299 0.52298922 0.42133437]
   [0.23824504

### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
matriz = np.random.rand(4,4)
matriz

Out[50]: array([[0.39938754, 0.82004309, 0.8479297 , 0.34945632],
       [0.05343779, 0.91066999, 0.23298761, 0.08410596],
       [0.38306268, 0.95737605, 0.4511024 , 0.32713189],
       [0.68858993, 0.17343464, 0.02836071, 0.68932207]])

In [0]:
matriz[0,-1], matriz[1,-2], matriz[2,-3], matriz[3,-4]

Out[69]: (0.34945631762278284,
 0.23298760951093123,
 0.9573760461251114,
 0.6885899301215254)

In [0]:
diag_princ = np.diag(matriz)
diag_sec = np.diag(np.fliplr(matriz))
media = np.mean([diag_princ,diag_sec])
std_matriz = np.std([diag_princ,diag_sec])

print("Diagonal principal:",diag_princ)
print("Diagonal secundária",diag_sec)
print("Média das diagonais", media)
print("Desvio padrão das diagonais:", std_matriz)

Diagonal principal: [0.39938754 0.91066999 0.4511024  0.68932207]
Diagonal secundária [0.34945632 0.23298761 0.95737605 0.68858993]
Média das diagonais 0.5848614878903982
Desvio padrão das diagonais: 0.24952774789809687


In [0]:
# tentar uma lógica do meu jeito
diag_princ = []
diag_sec = []
for i in range(len(matriz)):
  diag_princ.append(matriz[i][i])
  j = i+1
  diag_sec.append(matriz[i][-j])

media = np.mean([diag_princ,diag_sec])
std_matriz = np.std([diag_princ,diag_sec])

print("Diagonal principal:",diag_princ)
print("Diagonal secundária",diag_sec)
print("Média das diagonais", media)
print("Desvio padrão das diagonais:", std_matriz)

Diagonal principal: [0.39938754282975764, 0.9106699890591219, 0.4511024013013719, 0.6893220665525825]
Diagonal secundária [0.34945631762278284, 0.23298760951093123, 0.9573760461251114, 0.6885899301215254]
Média das diagonais 0.5848614878903982
Desvio padrão das diagonais: 0.24952774789809687
